export const GET_CONFERENCES = 'GET_CONFERENCES';
export const ADD_CONFERENCES = 'ADD_CONFERENCES';
export const GET_CONFERENCE = 'GET_CONFERENCE';
export const FILTER_CONFERENCE = 'FILTER_CONFERENCE';
export const CLEAR_FILTER = 'CLEAR_FILTER';
