export const ADD_WORKSHOP = 'ADD_WORKSHOP';
export const GET_WORKSHOP = 'GET_WORKSHOP';
export const UPDATE_WORKSHOP = 'UPDATE_WORKSHOP';
export const DELETE_WORKSHOP = 'DELETE_WORKSHOP';
export const SET_WORKSHOP = 'SET_WORKSHOP';
export const CLEAR_WORKSHOP = 'CLEAR_WORKSHOP';
